# This file is the Python type hints stub file for the sip extension module.
#
# Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
#
# This file is part of SIP.
#
# This copy of SIP is licensed for use under the terms of the SIP License
# Agreement.  See the file LICENSE for more details.
#
# This copy of SIP may also used under the terms of the GNU General Public
# License v2 or v3 as published by the Free Software Foundation which can be
# found in the files LICENSE-GPL2 and LICENSE-GPL3 included in this package.
#
# SIP is supplied WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


from typing import overload, TypeVar, Union


# Constants.
SIP_VERSION = ...       # type: int
SIP_VERSION_STR = ...   # type: str


# The bases for SIP generated types.
class wrappertype: ...
class simplewrapper: ...
class wrapper(simplewrapper): ...


# There is no explicit support for the buffer protocol
Buffer = TypeVar('Buffer', 'array', 'voidptr', str, bytes, bytearray)


# The different types that can be stored in an array.
ArrayElement = TypeVar('ArrayElement', simplewrapper, int, float)

# The array type.
class array:

    @overload
    def __getitem__(self, i: int) -> ArrayElement: ...

    @overload
    def __getitem__(self, s: slice) -> array: ...

    @overload
    def __setitem__(self, i: int, v: ArrayElement): ...

    @overload
    def __setitem__(self, s: slice, v: array): ...

    def __len__(self) -> int: ...


# The voidptr type.
class voidptr:

    def __init__(addr: Union[int, Buffer], size: int = -1, writeable: bool = True): ...

    def __int__(self) -> int: ...

    @overload
    def __getitem__(self, i: int) -> bytes: ...

    @overload
    def __getitem__(self, s: slice) -> 'voidptr': ...

    def __hex__(self) -> str: ...

    def __len__(self) -> int: ...

    def __setitem__(self, i: Union[int, slice], v: Buffer): ...

    def asarray(self, size: int = -1) -> array: ...

    # Python doesn't expose the capsule type.
    #def ascapsule(self) -> capsule: ...

    def asstring(self, size: int = -1) -> bytes: ...

    def getsize(self) -> int: ...

    def getwriteable(self) -> bool: ...

    def setsize(self, size: int): ...

    def setwriteable(self, bool): ...


# Remaining functions.
def cast(obj: simplewrapper, type: wrappertype) -> simplewrapper: ...
def delete(obj: simplewrapper): ...
def dump(obj: simplewrapper): ...
def enableautoconversion(type: wrappertype, enable: bool) -> bool: ...
def getapi(name: str) -> int: ...
def isdeleted(obj: simplewrapper) -> bool: ...
def ispycreated(obj: simplewrapper) -> bool: ...
def ispyowned(obj: simplewrapper) -> bool: ...
def setapi(name: str, version: int): ...
def setdeleted(obj: simplewrapper): ...
def setdestroyonexit(destroy: bool): ...
def settracemask(mask: int): ...
def transferback(obj: wrapper): ...
def transferto(obj: wrapper, owner: wrapper): ...
def unwrapinstance(obj: simplewrapper): ...
def wrapinstance(addr: int, type: wrappertype) -> simplewrapper: ...
