/*
 * The PEP 484 type hints generator for SIP.
 *
 * Copyright (c) 2016 Riverbank Computing Limited <info@riverbankcomputing.com>
 *
 * This file is part of SIP.
 *
 * This copy of SIP is licensed for use under the terms of the SIP License
 * Agreement.  See the file LICENSE for more details.
 *
 * This copy of SIP may also used under the terms of the GNU General Public
 * License v2 or v3 as published by the Free Software Foundation which can be
 * found in the files LICENSE-GPL2 and LICENSE-GPL3 included in this package.
 *
 * SIP is supplied WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */


#include <stdio.h>
#include <string.h>

#include "sip.h"


static void pyiEnums(sipSpec *pt, moduleDef *mod, classDef *scope,
        classList *defined, int indent, FILE *fp);
static void pyiVars(sipSpec *pt, moduleDef *mod, classDef *scope,
        classList *defined, int indent, FILE *fp);
static void pyiClass(sipSpec *pt, moduleDef *mod, classDef *cd,
        classList **defined, int indent, FILE *fp);
static void pyiCtor(sipSpec *pt, moduleDef *mod, ctorDef *ct, int overloaded,
        int sec, classList *defined, int indent, FILE *fp);
static void pyiCallable(sipSpec *pt, moduleDef *mod, memberDef *md,
        overDef *overloads, int is_method, classList *defined, int indent,
        FILE *fp);
static void pyiOverload(sipSpec *pt, moduleDef *mod, overDef *od,
        int overloaded, int is_method, int sec, classList *defined, int indent,
        FILE *fp);
static void pyiPythonSignature(sipSpec *pt, moduleDef *mod, signatureDef *sd,
        int need_self, int sec, classList *defined, FILE *fp);
static int pyiArgument(sipSpec *pt, moduleDef *mod, argDef *ad, int out,
        int need_comma, int sec, int names, int defaults, classList *defined,
        FILE *fp);
static void pyiType(sipSpec *pt, moduleDef *mod, argDef *ad, int sec,
        classList *defined, FILE *fp);
static void pyiDefaultValue(argDef *ad, FILE *fp);
static void prIndent(int indent, FILE *fp);
static int separate(int first, int indent, FILE *fp);
static void prClassRef(classDef *cd, moduleDef *mod, classList *defined,
        FILE *fp);
static void prEnumRef(enumDef *ed, moduleDef *mod, classList *defined,
        FILE *fp);
static int isDefined(classDef *cd, moduleDef *mod, classList *defined);
static int hasImplicitOverloads(signatureDef *sd);


/*
 * Generate the .pyi file.
 */
void generateTypeHints(sipSpec *pt, moduleDef *mod, const char *pyiFile)
{
    char *cp;
    int first;
    memberDef *md;
    classDef *cd;
    classList *defined;
    moduleListDef *mld;
    FILE *fp;

    /* Generate the file. */
    if ((fp = fopen(pyiFile, "w")) == NULL)
        fatal("Unable to create file \"%s\"\n", pyiFile);

    /* Write the header. */
    fprintf(fp,
"# The PEP 484 type hints stub file for the %s module.\n"
"#\n"
"# Generated by SIP %s\n"
        , mod->name
        , sipVersion);

    prCopying(fp, mod, "#");

    /*
     * Generate the imports. Note that we assume the super-types are the
     * standard SIP ones.
     */
    fprintf(fp,
"\n"
"\n"
"from typing import Any, Callable, Dict, List, Optional, overload, Set%s\n"
"\n"
"import sip\n"
"\n"
        , (pt->sigslots ? ", TypeVar, Union" : ""));

    /*
     * We import the root package so that we can forward reference any type by
     * specifying its fully qualified name.  This is necessary to support
     * mapped type templates where we have no idea what the context will be
     * when the template is expanded.
     */
    if ((cp = strchr(mod->fullname->text, '.')) == NULL)
    {
        fprintf(fp, "import %s\n", mod->fullname->text);
    }
    else
    {
        *cp = '\0';
        fprintf(fp, "import %s\n", mod->fullname->text);
        *cp = '.';
    }

    for (mld = mod->imports; mld != NULL; mld = mld->next)
    {
        if ((cp = strrchr(mld->module->fullname->text, '.')) == NULL)
        {
            fprintf(fp, "import %s\n", mld->module->name);
        }
        else
        {
            *cp = '\0';
            fprintf(fp, "from %s import %s\n", mld->module->fullname->text,
                    mld->module->name);
            *cp = '.';
        }
    }

    if (pt->sigslots)
        fprintf(fp,
"\n"
"\n"
"SIGNAL_T = TypeVar('SIGNAL_T')\n"
"SLOT_T = TypeVar('SLOT_T')\n"
            );

    /* Generate the types - enums and classes. */
    pyiEnums(pt, mod, NULL, NULL, 0, fp);

    // FIXME: Mapped types.
    defined = NULL;

    for (cd = pt->classes; cd != NULL; cd = cd->next)
    {
        if (cd->iff->module != mod)
            continue;

        if (isExternal(cd))
            continue;

        /* Only handle non-nested classes here. */
        if (cd->ecd != NULL)
            continue;

        pyiClass(pt, mod, cd, &defined, 0, fp);
    }

    pyiVars(pt, mod, NULL, defined, 0, fp);

    first = TRUE;

    for (md = mod->othfuncs; md != NULL; md = md->next)
    {
        // FIXME: Handle slots.
        if (md->slot != no_slot)
            continue;

        first = separate(first, 0, fp);

        pyiCallable(pt, mod, md, mod->overs, FALSE, defined, 0, fp);
    }

    fclose(fp);
}


/*
 * Generate the type hints for a class.
 */
static void pyiClass(sipSpec *pt, moduleDef *mod, classDef *cd,
        classList **defined, int indent, FILE *fp)
{
    int first, nr_overloads;
    classDef *nested;
    ctorDef *ct;
    memberDef *md;

    separate(TRUE, indent, fp);
    prIndent(indent, fp);
    fprintf(fp, "class %s(", cd->pyname->text);

    if (cd->supers != NULL)
    {
        classList *cl;

        for (cl = cd->supers; cl != NULL; cl = cl->next)
        {
            if (cl != cd->supers)
                fprintf(fp, ", ");

            prClassRef(cl->cd, mod, *defined, fp);
        }
    }
    else if (cd->supertype != NULL)
    {
        fprintf(fp, "%s", cd->supertype->text);
    }
    else if (cd->iff->type == namespace_iface)
    {
        fprintf(fp, "sip.simplewrapper");
    }
    else
    {
        fprintf(fp, "sip.wrapper");
    }

    fprintf(fp, "):\n");

    ++indent;

    pyiEnums(pt, mod, cd, *defined, indent, fp);

    /* Handle any nested classes. */
    for (nested = pt->classes; nested != NULL; nested = nested->next)
        if (nested->ecd == cd)
            pyiClass(pt, mod, nested, defined, indent, fp);

    pyiVars(pt, mod, cd, *defined, indent, fp);

    nr_overloads = 0;

    for (ct = cd->ctors; ct != NULL; ct = ct->next)
    {
        if (isPrivateCtor(ct))
            continue;

        ++nr_overloads;
    }

    first = TRUE;

    for (ct = cd->ctors; ct != NULL; ct = ct->next)
    {
        int implicit_overloads, overloaded;

        if (isPrivateCtor(ct))
            continue;

        implicit_overloads = hasImplicitOverloads(&ct->pysig);
        overloaded = (implicit_overloads || nr_overloads > 1);

        first = separate(first, indent, fp);

        pyiCtor(pt, mod, ct, overloaded, FALSE, *defined, indent, fp);

        if (implicit_overloads)
            pyiCtor(pt, mod, ct, overloaded, TRUE, *defined, indent, fp);
    }

    first = TRUE;

    for (md = cd->members; md != NULL; md = md->next)
    {
        // FIXME: Handle slots.
        if (md->slot != no_slot)
            continue;

        first = separate(first, indent, fp);

        pyiCallable(pt, mod, md, cd->overs, TRUE, *defined, indent, fp);
    }


    /*
     * Keep track of what has been defined so that forward references are no
     * longer required.
     */
    appendToClassList(defined, cd);
}


/*
 * Generate an ctor type hint.
 */
static void pyiCtor(sipSpec *pt, moduleDef *mod, ctorDef *ct, int overloaded,
        int sec, classList *defined, int indent, FILE *fp)
{
    int a;

    if (overloaded)
    {
        prIndent(indent, fp);
        fprintf(fp, "@overload\n");
    }

    prIndent(indent, fp);
    fprintf(fp, "def __init__(self");

    for (a = 0; a < ct->pysig.nrArgs; ++a)
        pyiArgument(pt, mod, &ct->pysig.args[a], FALSE, TRUE, sec, TRUE, TRUE,
                defined, fp);

    fprintf(fp, ") -> None: ...\n");
}


/*
 * Generate the APIs for all the enums in a scope.
 */
static void pyiEnums(sipSpec *pt, moduleDef *mod, classDef *scope,
        classList *defined, int indent, FILE *fp)
{
    enumDef *ed;

    for (ed = pt->enums; ed != NULL; ed = ed->next)
    {
        enumMemberDef *emd;

        if (ed->module != mod)
            continue;

        if (scope != NULL)
        {
            if (ed->ecd != scope)
                continue;
        }
        else if (ed->ecd != NULL || ed->emtd != NULL)
        {
            /* FIXME: Handle enums in mapped types. */
            continue;
        }

        separate(TRUE, indent, fp);

        if (ed->pyname != NULL)
        {
            prIndent(indent, fp);
            fprintf(fp, "class %s(int): ...\n", ed->pyname->text);
        }

        for (emd = ed->members; emd != NULL; emd = emd->next)
        {
            prIndent(indent, fp);
            fprintf(fp, "%s = ... # type: ", emd->pyname->text);

            if (ed->pyname != NULL)
                prEnumRef(ed, mod, defined, fp);
            else
                fprintf(fp, "int");

            fprintf(fp, "\n");
        }
    }
}


/*
 * Generate the APIs for all the variables in a scope.
 */
static void pyiVars(sipSpec *pt, moduleDef *mod, classDef *scope,
        classList *defined, int indent, FILE *fp)
{
    int first = TRUE;
    varDef *vd;

    for (vd = pt->vars; vd != NULL; vd = vd->next)
    {
        if (vd->module != mod)
            continue;

        if (vd->ecd != scope)
            continue;

        first = separate(first, indent, fp);

        prIndent(indent, fp);
        fprintf(fp, "%s = ... # type: ", vd->pyname->text);
        pyiType(pt, mod, &vd->type, FALSE, defined, fp);
        fprintf(fp, "\n");
    }
}


/*
 * Generate the type hints for a callable.
 */
static void pyiCallable(sipSpec *pt, moduleDef *mod, memberDef *md,
        overDef *overloads, int is_method, classList *defined, int indent,
        FILE *fp)
{
    int nr_overloads;
    overDef *od;

    /* Count the number of overloads. */
    nr_overloads = 0;

    for (od = overloads; od != NULL; od = od->next)
    {
        if (isPrivate(od))
            continue;

        if (od->common != md)
            continue;

        ++nr_overloads;
    }

    /* Handle each overload. */
    for (od = overloads; od != NULL; od = od->next)
    {
        int implicit_overloads, overloaded;

        if (isPrivate(od))
            continue;

        if (od->common != md)
            continue;

        implicit_overloads = hasImplicitOverloads(&od->pysig);
        overloaded = (implicit_overloads || nr_overloads > 1);

        pyiOverload(pt, mod, od, overloaded, is_method, FALSE, defined, indent,
                fp);

        if (implicit_overloads)
            pyiOverload(pt, mod, od, overloaded, is_method, TRUE, defined,
                    indent, fp);
    }
}


/*
 * Generate a single API overload.
 */
static void pyiOverload(sipSpec *pt, moduleDef *mod, overDef *od,
        int overloaded, int is_method, int sec, classList *defined, int indent,
        FILE *fp)
{
    int need_self;

    if (overloaded)
    {
        prIndent(indent, fp);
        fprintf(fp, "@overload\n");
    }

    if (is_method && isStatic(od))
    {
        prIndent(indent, fp);
        fprintf(fp, "@staticmethod\n");
    }

    prIndent(indent, fp);
    fprintf(fp, "def %s", od->common->pyname->text);

    need_self = (is_method && !isStatic(od));

    pyiPythonSignature(pt, mod, &od->pysig, need_self, sec, defined, fp);

    fprintf(fp, ": ...\n");
}


/*
 * Generate a Python argument.
 */
static int pyiArgument(sipSpec *pt, moduleDef *mod, argDef *ad, int out,
        int need_comma, int sec, int names, int defaults, classList *defined,
        FILE *fp)
{
    if (isArraySize(ad))
        return need_comma;

    if (sec && (ad->atype == slotcon_type || ad->atype == slotdis_type))
        return need_comma;

    if (need_comma)
        fprintf(fp, ", ");

    // FIXME: Don't have a name when arg is ellipsis.
    if (names)
        fprintf(fp, "%s: ", (ad->name != NULL ? ad->name->text : "arg"));

    pyiType(pt, mod, ad, sec, defined, fp);

    /*
     * Handle the default value but ignore it if it is an output only argument.
     */
    if (defaults && ad->defval && !out)
    {
        fprintf(fp, " = ");
        prcode(fp, "%M");
        pyiDefaultValue(ad, fp);
        prcode(fp, "%M");
    }

    return TRUE;
}


/*
 * Generate the default value of an argument.
 */
static void pyiDefaultValue(argDef *ad, FILE *fp)
{
    /* Use any explicitly provided documentation. */
    if (ad->docval != NULL)
    {
        prcode(fp, "%s", ad->docval);
        return;
    }

    /* Translate some special cases. */
    if (ad->defval->next == NULL && ad->defval->vtype == numeric_value)
    {
        if (ad->nrderefs > 0 && ad->defval->u.vnum == 0)
        {
            prcode(fp, "None");
            return;
        }

        if (ad->atype == bool_type || ad->atype == cbool_type)
        {
            prcode(fp, ad->defval->u.vnum ? "True" : "False");
            return;
        }
    }

    generateExpression(ad->defval, FALSE, fp);
}


/*
 * Generate the Python representation of a type.
 */
static void pyiType(sipSpec *pt, moduleDef *mod, argDef *ad, int sec,
        classList *defined, FILE *fp)
{
    const char *type_name;

    /* Use any explicit type. */
    if ((type_name = ad->hinttype) == NULL)
        type_name = ad->doctype;

    if (type_name != NULL)
    {
        fprintf(fp, "%s", type_name);
        return;
    }

    /* For classes and mapped types we need the default implementation. */
    if (ad->atype == class_type || ad->atype == mapped_type)
    {
        classDef *def_cd = NULL;
        mappedTypeDef *def_mtd = NULL;
        ifaceFileDef *iff;

        if (ad->atype == class_type)
        {
            iff = ad->u.cd->iff;

            if (iff->api_range == NULL)
            {
                /* There is only one implementation. */
                def_cd = ad->u.cd;
                iff = NULL;
            }
        }
        else
        {
            iff = ad->u.mtd->iff;

            if (iff->api_range == NULL)
            {
                /* There is only one implementation. */
                def_mtd = ad->u.mtd;
                iff = NULL;
            }
        }

        if (iff != NULL)
        {
            int def_api;

            /* Find the default implementation. */
            def_api = findAPI(pt, iff->api_range->api_name->text)->from;

            for (iff = iff->first_alt; iff != NULL; iff = iff->next_alt)
            {
                apiVersionRangeDef *avd = iff->api_range;

                if (avd->from > 0 && avd->from > def_api)
                    continue;

                if (avd->to > 0 && avd->to <= def_api)
                    continue;

                /* It's within range. */
                break;
            }

            /* Find the corresponding class or mapped type. */
            for (def_cd = pt->classes; def_cd != NULL; def_cd = def_cd->next)
                if (def_cd->iff == iff)
                    break;

            if (def_cd == NULL)
                for (def_mtd = pt->mappedtypes; def_mtd != NULL; def_mtd = def_mtd->next)
                    if (def_mtd->iff == iff)
                        break;
        }

        /* Now handle the correct implementation. */
        if (def_cd != NULL)
        {
            prClassRef(def_cd, mod, defined, fp);
        }
        else
        {
            /*
             * Give a hint that /HintType/ should be used, or there is no
             * default implementation.
             */
            type_name = "Any";

            if (def_mtd != NULL)
            {
                if (def_mtd->hinttype != NULL)
                    type_name = def_mtd->hinttype;
                else if (def_mtd->doctype != NULL)
                    type_name = def_mtd->doctype;
                else if (def_mtd->pyname != NULL)
                    type_name = def_mtd->pyname->text;
            }

            fprintf(fp, "%s", type_name);
        }

        return;
    }

    switch (ad->atype)
    {
    case enum_type:
        if (ad->u.ed->pyname != NULL)
            prEnumRef(ad->u.ed, mod, defined, fp);
        else
            type_name = "int";

        break;

    case capsule_type:
        type_name = scopedNameTail(ad->u.cap);
        break;

    case struct_type:
    case void_type:
        type_name = "sip.voidptr";
        break;

    case signal_type:
        type_name = "SIGNAL_T";
        break;

    case slot_type:
        type_name = "Union[SLOT_T, SIGNAL_T]";
        break;

    case rxcon_type:
    case rxdis_type:
        if (sec)
        {
            type_name = "Callable";
        }
        else
        {
            /* The class should always be found. */
            if (pt->qobject_cd != NULL)
                prClassRef(pt->qobject_cd, mod, defined, fp);
            else
                type_name = "Any";
        }

        break;

    case qobject_type:
        type_name = "QObject";
        break;

    case ustring_type:
    case string_type:
    case sstring_type:
    case wstring_type:
    case ascii_string_type:
    case latin1_string_type:
    case utf8_string_type:
        type_name = "str";
        break;

    case byte_type:
    case sbyte_type:
    case ubyte_type:
    case ushort_type:
    case uint_type:
    case long_type:
    case longlong_type:
    case ulong_type:
    case ulonglong_type:
    case short_type:
    case int_type:
    case cint_type:
        type_name = "int";
        break;

    case float_type:
    case cfloat_type:
    case double_type:
    case cdouble_type:
        type_name = "float";
        break;

    case bool_type:
    case cbool_type:
        type_name = "bool";
        break;

    case pyobject_type:
        type_name = "object";
        break;

    case pytuple_type:
        type_name = "Tuple";
        break;

    case pylist_type:
        type_name = "List";
        break;

    case pydict_type:
        type_name = "Dict";
        break;

    case pycallable_type:
        type_name = "Callable";
        break;

    case pyslice_type:
        type_name = "slice";
        break;

    case pytype_type:
        type_name = "type";
        break;

    case pybuffer_type:
        type_name = "buffer";
        break;

    case ellipsis_type:
        type_name = "...";
        break;

    case slotcon_type:
    case anyslot_type:
        type_name = "SLOT_T";
        break;

    default:
        type_name = "Any";
    }

    if (type_name != NULL)
        fprintf(fp, "%s", type_name);
}


/*
 * Generate a scoped Python name.
 */
void prScopedPythonName(FILE *fp, classDef *scope, const char *pyname)
{
    if (scope != NULL)
    {
        prScopedPythonName(fp, scope->ecd, NULL);
        fprintf(fp, "%s.", scope->pyname->text);
    }

    if (pyname != NULL)
        fprintf(fp, "%s", pyname);
}


/*
 * Generate a Python signature.
 */
static void pyiPythonSignature(sipSpec *pt, moduleDef *mod, signatureDef *sd,
        int need_self, int sec, classList *defined, FILE *fp)
{
    const char *type_name;
    int need_comma, is_res, nr_out, a;

    if (need_self)
    {
        fprintf(fp, "(self");
        need_comma = TRUE;
    }
    else
    {
        fprintf(fp, "(");
        need_comma = FALSE;
    }

    nr_out = 0;

    for (a = 0; a < sd->nrArgs; ++a)
    {
        argDef *ad = &sd->args[a];

        if (isOutArg(ad))
            ++nr_out;

        if (!isInArg(ad))
            continue;

        need_comma = pyiArgument(pt, mod, ad, FALSE, need_comma, sec, TRUE,
                TRUE, defined, fp);
    }

    fprintf(fp, ")");

    if ((type_name = sd->result.hinttype) == NULL)
        type_name = sd->result.doctype;

    is_res = !((sd->result.atype == void_type && sd->result.nrderefs == 0) ||
            (type_name != NULL && type_name[0] == '\0'));

    if (is_res || nr_out > 0)
    {
        fprintf(fp, " -> ");

        if ((is_res && nr_out > 0) || nr_out > 1)
            fprintf(fp, "(");

        if (is_res)
            need_comma = pyiArgument(pt, mod, &sd->result, TRUE, FALSE, sec,
                    FALSE, FALSE, defined, fp);
        else
            need_comma = FALSE;

        for (a = 0; a < sd->nrArgs; ++a)
        {
            argDef *ad = &sd->args[a];

            if (isOutArg(ad))
                /* We don't want the name in the result tuple. */
                need_comma = pyiArgument(pt, mod, ad, TRUE, need_comma, sec,
                        FALSE, FALSE, defined, fp);
        }

        if ((is_res && nr_out > 0) || nr_out > 1)
            fprintf(fp, ")");
    }
    else
    {
        fprintf(fp, " -> None");
    }
}


/*
 * Generate the required indentation.
 */
static void prIndent(int indent, FILE *fp)
{
    while (indent--)
        fprintf(fp, "    ");
}


/*
 * Generate a newline if not already done.
 */
static int separate(int first, int indent, FILE *fp)
{
    if (first)
        fprintf(fp, (indent ? "\n" : "\n\n"));

    return FALSE;
}


/*
 * Generate a class reference, including its owning module if necessary and
 * handling forward references if necessary.
 */
static void prClassRef(classDef *cd, moduleDef *mod, classList *defined,
        FILE *fp)
{
    int is_defined = isDefined(cd, mod, defined);

    if (!is_defined)
        fprintf(fp, "'");

    if (cd->iff->module != mod)
        fprintf(fp, "%s.", cd->iff->module->name);

    prScopedPythonName(fp, cd->ecd, cd->pyname->text);

    if (!is_defined)
        fprintf(fp, "'");
}


/*
 * Generate an enum reference, including its owning module if necessary and
 * handling forward references if necessary.
 */
static void prEnumRef(enumDef *ed, moduleDef *mod, classList *defined,
        FILE *fp)
{
    int is_defined = (ed->ecd != NULL && isDefined(ed->ecd, mod, defined));

    if (!is_defined)
        fprintf(fp, "'");

    if (ed->module != mod)
        fprintf(fp, "%s.", ed->module->name);

    prScopedPythonName(fp, ed->ecd, ed->pyname->text);

    if (!is_defined)
        fprintf(fp, "'");
}


/*
 * Check if a class has been defined.
 */
static int isDefined(classDef *cd, moduleDef *mod, classList *defined)
{
    /* A class in another module would have been imported. */
    if (cd->iff->module != mod)
        return TRUE;

    while (defined != NULL)
    {
        if (defined->cd == cd)
            return TRUE;

        defined = defined->next;
    }

    return FALSE;
}


/*
 * See if a signature has implicit overloads.
 */
static int hasImplicitOverloads(signatureDef *sd)
{
    int a;

    for (a = 0; a < sd->nrArgs; ++a)
    {
        argDef *ad = &sd->args[a];

        if (!isInArg(ad))
            continue;

        if (ad->atype == rxcon_type || ad->atype == rxdis_type)
            return TRUE;
    }

    return FALSE;
}
