# SPDX-License-Identifier: BSD-2-Clause

# Copyright (c) 2026 Phil Thompson <phil@riverbankcomputing.com>


# The builtin Python exceptions across all supported versions of Python.
PYTHON_EXCEPTIONS = (
    'BaseException',
    'BaseExceptionGroup',
    'Exception',

    'ArithmeticError',
    'AssertionError',
    'AttributeError',
    'BlockingIOError',
    'BrokenPipeError',
    'BufferError',
    'ChildProcessError',
    'ConnectionAbortedError',
    'ConnectionError',
    'ConnectionRefusedError',
    'ConnectionResetError',
    'EOFError',
    'FileExistsError',
    'FileNotFoundError',
    'FloatingPointError',
    'GeneratorExit',
    'ImportCycleError',
    'ImportError',
    'IndentationError',
    'IndexError',
    'InterruptedError',
    'IsADirectoryError',
    'KeyError',
    'KeyboardInterrupt',
    'LookupError',
    'MemoryError',
    'ModuleNotFoundError',
    'NameError',
    'NotADirectoryError',
    'NotImplementedError',
    'OSError',
    'OverflowError',
    'PermissionError',
    'ProcessLookupError',
    'PythonFinalizationError',
    'RecursionError',
    'ReferenceError',
    'RuntimeError',
    'StopAsyncIteration',
    'StopIteration',
    'SyntaxError',
    'SystemError',
    'SystemExit',
    'TabError',
    'TimeoutError',
    'TypeError',
    'UnboundLocalError',
    'UnicodeDecodeError',
    'UnicodeEncodeError',
    'UnicodeError',
    'UnicodeTranslateError',
    'ValueError',
    'ZeroDivisionError',

    'Warning',
    'BytesWarning',
    'DeprecationWarning',
    'EncodingWarning',
    'FutureWarning',
    'ImportWarning',
    'PendingDeprecationWarning',
    'ResourceWarning',
    'RuntimeWarning',
    'SyntaxWarning',
    'UnicodeWarning',
    'UserWarning',
)
